### ISSUE TITLE
请问pull之后还push吗？

### ISSUE THREAD

**Issue by qingyuan0o0** [DeppWang/youdaonote-pull#1]
请问pull之后还push吗？

**Comment by DeppWang** [comment]
> 请问pull之后还push吗？
没理解你的意思，你的意思是如何将本地笔记再同步（push）到有道云笔记上去吗？这个功能还在开发中

**Comment by qingyuan0o0** [comment]
是这个意思，但是我刚刚看到的另外一个方法是，使用绑定的邮箱发送邮件至save@note.youdao.com，即可将邮件保存至笔记

**Comment by DeppWang** [comment]
你这个方法我还没试过，但也比较麻烦吧，后续我会使用有道云笔记提供的 API，开发一个 push.py，直接运行 push.py 就能将本地指定文件夹同步到有道云笔记直接文件夹了。

**Comment by qingyuan0o0** [comment]
嗯，如果有push的话是是否可以上传*.md的笔记？

**Comment by DeppWang** [comment]
这个肯定可以哈



    
    
        font{
            line-height: 1.6;
        }
    
公众号：DeppWang个人博客：https://depp.wang个人主页：https://github.com/deppwang

     



            在2019年09月19日 16:36，情缘 写道： 嗯，如果有push的话是是否可以上传*.md的笔记？



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/DeppWang/youdaonote-pull/issues/1?email_source=notifications\u0026email_token=AFHWQJKBMNJINWPY7HX2BMLQKM22DA5CNFSM4IYGIG72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7CWBMA#issuecomment-533029040",

"url": "https://github.com/DeppWang/youdaonote-pull/issues/1?email_source=notifications\u0026email_token=AFHWQJKBMNJINWPY7HX2BMLQKM22DA5CNFSM4IYGIG72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7CWBMA#issuecomment-533029040",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by qingyuan0o0** [comment]
主要是笔记中可能涉及到只想给特定的人看，分享加密码还有归类等骚操作，所以github不一定适合。

**Comment by DeppWang** [comment]
理解了，我后续开发一下上传到有道云笔记的脚本，或者你也可以参考 http://note.youdao.com/open/，自己写个

**Comment by qingyuan0o0** [comment]
还没那本事写，要写就要从头学起。。。。

**Comment by qingyuan0o0** [comment]
测试pull的时候发生错误
正在 pull，请稍后 ....
Traceback (most recent call last):
  File "pullALL.py", line 168, in <module>
    sess.getAll(d['localDir'], d['ydnoteDir'])
  File "pullALL.py", line 53, in getAll
    self.getFileRecursively(dirId, localDir)
  File "pullALL.py", line 98, in getFileRecursively
    total = jsonObj['count']
KeyError: 'count'

**Comment by qingyuan0o0** [comment]
刚刚抓包了数据想说在本地写好md，然后通过上传的方式，检查抓包结果看到一个json
{v: 15492, tags: [{dateupdated: "1400***000", reserved: "", name: "172.255.52.112",…},…]}
tags:
[{dateupdated: "140***4000", reserved: "", name: "172.255.52.112",…},…]
{dateupdated: "140***4000", reserved: "", name: "172.255.52.112",…}
{dateupdated: "139***6823", reserved: "", name: "172.24.66.100",…}
{dateupdated: "139***6152", reserved: "", name: "172.24.88.30", id: "*****2583D1D49089ACF76C28EED6613",…}
{dateupdated: "139***2118", reserved: "", name: "172.24.66.2", id: "*****7EB08F147D69346B893574D6586",…}
{dateupdated: "139***6179", reserved: "", name: "密码要注意", id: "*****48BADF54A3FA790785F95EC8560",…}
{dateupdated: "139***4751", reserved: "", name: "数据", id: "*****4433FDE43D8AD2E53FD1B07B4B2",…}
{dateupdated: "141***0934", reserved: "", name: "总结", id: "*****1C042D9456DBFB10988580AEB89",…}
{dateupdated: "139***8179", reserved: "", name: "172.24.86.1", id: "*****A8DDBB146E8994A4FBF77D92000",…}
{dateupdated: "139***4751", reserved: "", name: "备份", id: "*****48FA26045D1BD1A5524FB652BB4",…}

**Comment by DeppWang** [comment]
- 你在网页版试试登陆是否需要验证码，如果需要的话，就是 ip
被封了。 https://note.youdao.com/signIn/index.html 
- 如果是 ip 被封，运行 pullAll.sh 应该会提示 「请检查账号密码是否正确；也可能因操作频繁导致 ip 被封，请切换网络或等待一段时间后重试！」，你发的报错没有提示这个，我这里 ip 正好被封了，无法复现你这个报错
- 你可以用微信有道云笔记公众号绑定一下账号，如果登录成功，微信会有提示，如果登录成功了，还报错的话，就是代码问题，你再反馈我一下
- 你可以用 pull.sh 
- 你说的抓包问题，没有理解到你的意思

**Comment by qingyuan0o0** [comment]
微信已经绑定，登陆3次，提示3次，都是同样的报错，而pull.py提示2个id都有问题的报错，但是事实上，已根据图抓到正确id了，还是这么提示就没再次尝试了

**Comment by qingyuan0o0** [comment]
我觉得可以避免被封的操作就是记录cookies，每次都去登陆比较不靠谱，多次操作容易被封

**Comment by DeppWang** [comment]
- 我刚测试了 pull.py，没有问题。你可能是哪里写错了。
- 原来打算利用 openAPI 实现上传操作，前两天发现接口只支持笔记，不支持 Markdown，所以 push.sh 后续也不能开发了，如果你有兴趣开发，可以自己鼓捣鼓捣

**Comment by qingyuan0o0** [comment]
上传附件或图片
l URL：http://[baseURL]/yws/open/resource/upload.json

l 请求方式：POST

l Content-Type：multipart/form-data

l 支持格式：JSON

l 是否需要用户认证：是 
支持上传  filename.md，上传到某个目录下就是了

**Comment by DeppWang** [comment]
如果只修改了 md 的话，需要先删除，再重新上传，但没有提供删除附件的接口

**Comment by DeppWang** [comment]
consumerKey: d27ad4d7863fac1dc7a415e613483392, consumerSecret: 4d0bd6cc6889f87145bc3b61c48a6505, redirect_uri: http://dev.maxthread.com . 这个 py 里面写好了，https://github.com/DeppWang/youdaonotepy/blob/master/demo2.py
